name: My List - Check titles expiring on Netflix

on:
  push:
    paths:
    - '**.json'

  workflow_dispatch:

jobs:
  mylist-checkexpiration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check titles (from my list) expiring on Netflix
        id: check_titlesexpiration
        run: |
          cd mylist
          python check_expire.py

      - name: Get Daily Date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Commit changes
        if: ${{ env.Expiring }} != 'None'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: MyList Expirations Update ${{ steps.date.outputs.date }}
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          disable_globbing: true
